### ISSUE TITLE
Error in pleeease-cli 4.0.0 when trying to compile or watch

### ISSUE THREAD

**Issue by oilvier** [iamvdo/pleeease-cli#12]
HI,

I've just updated pleeease-cli and pleeease (4.0.0 and 4.0.1) and I can't compile or watch anymore.
```
C:\Users\Olivier\AppData\Roaming\npm\node_modules\pleeease-cli\node_modules\pleeease\node_modules\postcss-import\index.js:14
var resolvedPromise = new Promise(function(resolvePromise) {
                          ^
ReferenceError: Promise is not defined
    at Object.<anonymous> (C:\Users\Olivier\AppData\Roaming\npm\node_modules\pleeease-cli\node_modules\pleeease\node_modules\postcss-import\index.js:14:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Olivier\AppData\Roaming\npm\node_modules\pleeease-cli\node_modules\pleeease\lib\processors.js:7:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

And here's my config file : 
```
{
	"in": [
		"build/bootstrap.scss"
	],
	"out": "screen.css",
	"browsers": ["last 3 versions", "opera 12.1", "Android 2.3", "ie 8"],
	"rem": true,
	"sass": true,
	"import": false,
	"minifier": true,
	"mqpacker": false,
	"sourcemaps": false,
	"next": {
		"customProperties": true,
		"customMedia": true
	}
}
```

**Comment by iamvdo** [comment]
Which Node.js version ?

**Comment by oilvier** [comment]
Well, I don't know why I switched back to v0.10.28, maybe when I updated to Windows 10.
Anyway it works fine with node.js 4.1.1.

Sorry for the trouble !

**Comment by iamvdo** [comment]
OK, great. ;)
