### ISSUE TITLE
Pleease fails in node v5 due to "missing dependency"

### ISSUE THREAD

**Issue by anselmh** [iamvdo/pleeease-cli#14]
The current version of pleeease-cli does not work anymore in node v5. It seems it has something to do with the (nested) pleeease dependency. Not sure how to solve this so no PR but only an issue. Sorry.

```
> pleeease compile styles.css -t styles.min.css

module.js:339
    throw err;
    ^

Error: Cannot find module '../node_modules/pleeease/package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/anselm/localhost/project/node_modules/pleeease-cli/bin/pleeease:8:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/anselm/.nvm/versions/node/v5.0.0/bin/node" "/Users/anselm/.nvm/versions/node/v5.0.0/bin/npm" "run" "css"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! `pleeease compile styles.css -t styles.min.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiya-website@1.0.0 css script 'pleeease compile styles.css -t styles.min.css'.
npm ERR! This is most likely a problem with the hiya-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pleeease compile styles.css -t styles.min.css
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/anselm/.nvm/versions/node/v5.0.0/bin/node" "/Users/anselm/.nvm/versions/node/v5.0.0/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
```

**Comment by yaycmyk** [comment]
@anselmh I'm running node 5 and am not seeing this issue. Try blowing away your node modules and reinstalling:

```bash
rm -rf node_modules/
npm i
```

**Comment by anselmh** [comment]
Hm that's exactly what I did. It has a flat dependency tree now, can this be the issue?

**Comment by yaycmyk** [comment]
@anselmh It's `pleeease-compile styles.css -t styles.min.css` note the dash between pleeease and compile, one whole phrase :)

**Comment by anselmh** [comment]
Oh, that’s indeed fixing it. Thanks so much, @yaycmyk.
